### ISSUE TITLE
Not working with WC 3.1.x?

### ISSUE THREAD

**Issue by codestylist** [GoWP/woocommerce-variations-apply-all#1]
Hello guys. Nice project! But it seems your code is not working anymore with the latest WC version 3.1.2.
This means, there is no link anmore behind "regular price",
Would you like to have a look and maybe updating your script? Because it would be very helpful ;-)
Thanks in advance!

**Comment by karpstrucking** [comment]
Hey @codestylist,

This entire snippet is no longer necessary as WooCommerce has added built-in support for the bulk editing of variations. While editing your product, after having added one or more variations, the “Add Variation” drop-down at the top of the Variations tab also includes a number of bulk edit options; you can set both regular and sale prices or modify either, increasing or decreasing by a percentage or set amount, for example.

[https://www.gowp.com/blog/apply-the-price-of-a-woocommerce-product-variation-to-all-variations-of-the-same-product/](https://www.gowp.com/blog/apply-the-price-of-a-woocommerce-product-variation-to-all-variations-of-the-same-product/)
